//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MazeWalker.rc
//
#define IDD_DIALOG_SENSORS              1
#define IDD_DIALOG_DEVICES              1
#define IDD_DIALOG_API                  1
#define ID_SETPORT                      3
#define IDD_DIALOG_SHADERS              9
#define IDD_DIALOG_ADVANCED             9
#define IDC_CURSOR1                     101
#define IDD_DIALOG1                     102
#define IDD_MAIN                        102
#define IDI_ICON1                       103
#define IDD_DIALOG2                     104
#define IDD_DIALOG_ABOUT                104
#define IDR_MENU1                       105
#define IDD_DIALOG3                     107
#define IDD_DIALOG_KEYBOARD             107
#define IDD_DIALOG4                     108
#define IDD_DIALOG_Other                108
#define IDD_DIALOG5                     109
#define IDD_DIALOG_COMM                 111
#define IDD_DIALOG_SYNC                 112
#define IDI_ICON2                       113
#define IDB_BITMAP1                     114
#define IDD_DIALOG6                     115
#define IDD_DIALOG_OCULUS               116
#define IDD_DIALOG_VIEW_OPTIONS         117
#define IDC_COMBO1                      1001
#define IDC_CHECK1                      1002
#define IDC_ORIENTATION_COMBO           1002
#define IDC_COMBO2                      1003
#define IDC_iUpDownAxis                 1003
#define IDC_iMoveAxis                   1004
#define IDC_CHECK2                      1005
#define IDC_iStrafeAxis                 1005
#define IDC_BUTTON1                     1006
#define IDC_SIMPLE_RENDERCHECK          1006
#define IDC_FILENAME                    1007
#define IDC_CHECK3                      1008
#define IDC_FIXED_CAMERA_CHECK          1008
#define IDC_FIXED_CAMERA_X_CHECK        1008
#define IDC_CHECK4                      1009
#define IDC_FIXED_CAMERA_CHECK2         1009
#define IDC_FIXED_CAMERA_Z_CHECK        1009
#define IDC_FILENAME2                   1010
#define IDC_BUTTON2                     1011
#define IDC_EDIT1                       1012
#define IDC_CHECK5                      1013
#define IDC_SENSORPORTEDIT2             1013
#define IDC_CustomHeight                1013
#define IDC_EDIT_CustomHeight           1013
#define IDC_STATIC1                     1014
#define IDC_SENSORPORTEDIT3             1014
#define IDC_triggerGroup                1014
#define IDC_LOGO                        1015
#define IDC_MES                         1016
#define IDC_CONT                        1017
#define IDC_CHECK6                      1018
#define IDC_AUTOLOGCHECK                1018
#define IDC_COMBO3                      1019
#define IDC_BUTTON3                     1020
#define IDC_CHECK7                      1021
#define IDC_BUTTON4                     1022
#define IDC_FILENAME3                   1023
#define IDC_CHECK8                      1024
#define IDC_CHECK9                      1025
#define IDC_BUTTON5                     1027
#define IDC_BUTTON6                     1028
#define IDC_BUTTON7                     1029
#define IDC_BUTTON8                     1030
#define IDC_BUTTON9                     1031
#define IDC_BUTTON10                    1032
#define IDC_BUTTON11                    1033
#define IDC_BUTTON12                    1034
#define IDC_BUTTON13                    1035
#define IDC_BUTTON14                    1036
#define IDC_BUTTON15                    1037
#define IDC_BUTTON16                    1038
#define IDC_BUTTON17                    1039
#define IDC_BUTTON19                    1041
#define IDC_BUTTON20                    1042
#define IDC_BUTTON21                    1043
#define IDC_RestoreDefault              1044
#define IDC_BUTTON18                    1045
#define IDC_BUTTON22                    1046
#define IDC_KEYBOARD_CANCEL             1046
#define IDC_CHECK10                     1047
#define IDC_AMBIENT_COMBO               1051
#define IDC_MAXLIGHTS_COMBO             1052
#define IDC_SHADER_CANCEL               1053
#define IDC_SHADER_OK                   1054
#define IDC_SHADER_DIFFUSE_CHECK        1055
#define IDC_SHADER_SPECULAR_CHECK       1056
#define IDC_SHADER_TEXTURES_CHECK       1057
#define IDC_SHADER_OBJECTS_CHECK        1058
#define IDC_BORDERLESS_CHECK            1059
#define IDC_Sensor_CHECK1               1060
#define IDC_SENSOR_CHECK2               1061
#define IDC_SENSOR_CHECK3               1062
#define IDC_SENSORPORTEDIT1             1065
#define IDC_LOCALCHECK1                 1067
#define IDC_LOCALCHECK2                 1068
#define IDC_DEVKEYSCHECK                1068
#define IDC_LOCALCHECK3                 1069
#define ID_CANCEL                       1069
#define ID_Default                      1070
#define IDC_Interactive                 1071
#define IDC_INTERACTIVECHECK            1071
#define IDC_InteractiveCaption          1072
#define IDC_ScoreBox_Caption            1072
#define IDC_BUTTON23                    1073
#define IDC_FPSCHECK                    1073
#define IDC_BUTTON24                    1074
#define IDC_InteractiveCaption2         1074
#define IDC_jMoveAxis                   1075
#define IDC_BUTTON_INTERACT             1075
#define IDC_HIDE_RENDEREDMAZE_CHECK     1075
#define IDC_HIDE_RENDERED_MAZE_CHECK    1075
#define IDC_jStrafeAxis                 1076
#define IDC_BUTTON_INTERACT2            1076
#define IDC_BUTTON_RESTART              1076
#define IDC_DISABLE_GRAVITY_CHECK       1076
#define IDC_jUpDownAxis                 1077
#define IDC_BUTTON_RESTART2             1077
#define IDC_BUTTON_NEXT                 1077
#define IDC_InteractiveCaption3         1077
#define IDC_iLeftRightAxis              1078
#define IDC_jLeftRightAxis              1079
#define IDC_jJumpButton                 1080
#define IDC_jInteractButton             1081
#define IDC_DEFAULT                     1082
#define IDC_JOYSTICK_DEFAULT1           1082
#define IDD_JOYSTICK                    1083
#define IDD_DIALOG_JOYSTICK             1083
#define IDC_SENSELR                     1083
#define IDC_SENSEUD                     1084
#define IDC_WaitCheck                   1085
#define IDC_SENSEMOVE                   1085
#define IDC_PORTCOMBO                   1086
#define IDC_SENSESTRAFE                 1086
#define IDC_BAUDRATECOMBO               1087
#define IDC_JOYSTICK_DEFAULT2           1087
#define IDC_PARITYCOMBO                 1088
#define IDC_JOYSTICK_API                1088
#define IDC_STOPBITSCOMBO               1089
#define IDC_SerialCheck                 1090
#define IDC_LISTENCHECK                 1091
#define IDC_IPADDRESS1                  1092
#define IDC_LPT_CHECK                   1092
#define IDC_IPADDRESS2                  1093
#define IDC_IPADDRESS3                  1094
#define IDC_EDIT_TRIGGERCHAR            1095
#define IDC_CUECOMBO                    1096
#define IDC_JOYCUECOMBO                 1097
#define IDC_JOYNUMCOMBO                 1098
#define IDC_SKIPBUTTONCHECK             1099
#define IDC_MYIMAGE                     1100
#define IDC_VERSIONS                    1101
#define IDC_DEVICECHECK                 1102
#define IDC_DEVICECHECK2                1103
#define IDC_DEVICECHECK3                1104
#define IDC_SKIPERRORCHECK              1105
#define IDC_SKIPWarningCHECK            1105
#define IDC_CHECK_MSAA                  1106
#define IDC_CHECK_VSYNC                 1107
#define IDC_OCULUS_CHECK                1107
#define IDC_CHECK_ANISO                 1108
#define IDC_FOV_EDIT                    1109
#define IDC_WAIT_FOR_CONNECTION_CHECK   1110
#define IDC_PRESEPECTIVE_COMBO          1112
#define IDC_TOPDOWN_MOUSE_CHECK         1113
#define IDC_EDIT2                       1116
#define IDC_EDIT_HEIGHT                 1116
#define IDC_EDIT_FIXZ                   1117
#define IDC_SCOREBAR_COMBO              1117
#define IDC_EDIT_HEIGHT3                1118
#define IDC_EDIT_FIXX                   1118
#define IDC_EDIT_CustomWidth            1118
#define IDC_STATICPORTLABEL             1119
#define IDC_STATICCURRENTPORT           1120
#define IDC_SETLPTPORT                  1121
#define IDC_EDITLPT                     1122
#define IDC_EDITLPT_DELAY               1123
#define IDC_STATIC_COPYRIGHT            1123
#define IDC_SETLPTPORT2                 1124
#define IDC_SETLPT_DELAY                1124
#define ID_INFO_ABOUT                   40001
#define ID_FILE_EXIT                    40002
#define ID_FILE_START                   40004
#define ID_INFO_CONTROLS                40005
#define ID_OTHER_CONTROLS               40006
#define ID_ADVANCED_SHADEROPTIONS       40007
#define ID_ADVANCED_SENSORINPUTS        40008
#define ID_ADVANCED_SENSOROPTIONS       40009
#define ID_ADVANCED_OTHER               40010
#define ID_ADVANCED_JOYSTICKOPTIONS     40011
#define ID_ADVANCED_JOYSTICK            40012
#define ID_ADVANCED_SERIALOPTIONS       40013
#define ID_DIALOG_COMM                  40014
#define IDD_ADVANCED_SYNC               40015
#define ID_ADVANCED_SYNC                40016
#define ID_HELP_MAZEUPDATEUTILITY       40017
#define ID_ADVANCED_OCULUSSETTINGS      40018
#define ID_DIALOG_OCULUS                40019
#define IDD_ADVANCED_OCULUS             40020
#define ID_ADVANCED_OCULUS              40021
#define ID_ADVANCED_PRESPECTIVESETTINGS 40022
#define ID_ADVANCED_PERSPECTIVESETTINGS 40023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40024
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
